### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by DanielBeckDK** [tiagosiebler/bybit-api#130]
My apologies if this question is inappropriate or misplaced but I was wondering how, other than reading every line of code throughout the entire project, one can determine that this npm package is safe to use?

What I mean is, since you have to provide you API_KEY and API_SECRET to interact with your bybit account, could this package not include some code somewhere that would send my private API information to someone, allowing them to interact with my bybit account?

This seems to be a pretty cool package and I am trying it out as I'm writing this and it works great :D! But as one should be, I am cautious when dealing with my private API informations from bybit

**Comment by tiagosiebler** [comment]
No need to apologise! This kind of question is both very appropriate and very important. Technically that kind of abuse can happen - in particular with package dependencies through what's often called a supply chain attack. 

In my opinion, there are two perspectives to dealing with this from your side: 
1. doing what you can to prevent your api credentials from being shared
    - review 1st party code your credentials are going to be exposed to (e.g. my API connectors that you are about to use - fortunately there isn't too much code compared to some projects out there)
    - review 3rd party code that may get exposed to your credentials (e.g. the dependencies used by my connectors, which I do try to keep minimal & reviewed for that reason).
    - evaluate any other places where your credentials could be exposed (e.g. the environment(s) your credentials will be exposed to)
2. making it as difficult & unlikely as possible for abuse to happen, if credentials ever fall into the wrong hands
    - always make API credentials as restrictive as possible. 
    - only grant the necessary privileges (if the exchange supports it)
    - always set IP restrictions. Always!

The second point is particularly important. Would be curious if the community also has other recommendations, besides best practices on the account level (such having 2 factor auth enabled).

Glad you're otherwise enjoying the package! Some aspects are still incomplete (spot implementation and introducing better typings), so contributions via pull requests are always welcome.

**Comment by DanielBeckDK** [comment]
Thank you @tiagosiebler for this speedy and perfect answer! I very much appreciate it :D!
