### ISSUE TITLE
SpotClient.getServerTime returns undefined

### ISSUE THREAD

**Issue by DavidKrpt** [tiagosiebler/bybit-api#147]
Hi, thanks for the package! I noticed that SpotClient.getServerTime returns undefined. I think in spot-client.js
```
            const result = yield this.get('/spot/v1/time');
            return result.serverTime;
```
the line
`return result.serverTime;`
should be replaced with
`return result.result.serverTime;`
because the endpoint https://api.bybit.com/spot/v1/time returns an object like this one

```
{
   "ret_code":0,
   "ret_msg":"",
   "ext_code":null,
   "ext_info":null,
   "result":{
      "serverTime":1651155074458
   }
}
```

Seems like an easy PR, but I can't do it right now, so I'll post instead

**Comment by tiagosiebler** [comment]
Thanks for pointing this out! Much of the spot client is currently being revised. I've been stalled for bandwidth but I'll make sure to include this.

**Comment by tiagosiebler** [comment]
@DavidKrpt  Will be fixed in #150. Are you integrating spot at the moment? Do you have bandwidth to help validate the new version works as expected (& remains consistent with the old)? It's currently published as beta: `npm i bybit-api@beta`.

I was cautious of accidentally introducing any breaking changes - especially if undocumented. Except for removing previously deprecated methods, I don’t expect any but if anything has slipped through the cracks, now’s a great time to find & report it. 

Will be looking to publish it properly in the coming few days. Thanks!

**Comment by DavidKrpt** [comment]
@tiagosiebler, thanks! I ended up using a custom method for spot requests and moved on to the next thing. Eventually I will go back and refactor spot integration to use the package methods, but it most likely won't happen in the next few days, sorry about that

**Comment by tiagosiebler** [comment]
> @tiagosiebler, thanks! I ended up using a custom method for spot requests and moved on to the next thing. Eventually I will go back and refactor spot integration to use the package methods, but it most likely won't happen in the next few days, sorry about that

No worries, understandable - thanks for the quick response!
