### ISSUE TITLE
"crypto" module seems depreciated

### ISSUE THREAD

**Issue by Amais26** [tiagosiebler/bybit-api#157]
Got error when compiling

<img width="837" alt="image" src="https://user-images.githubusercontent.com/91221269/177660706-918d59d4-a8a2-4fdb-8992-545a76c1964b.png">

It seems to be bound to file node-support.js line 13

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/91221269/177660950-3a14f0f7-7223-49fb-820b-02aec72f297c.png">

https://www.npmjs.com/package/crypto

How do you handle this error ?

**Comment by tiagosiebler** [comment]
Which nodejs version are you using? It's a built-in module included with node, that's why it's not listed in the package dependencies. 

In case you're trying to use this in a frontend environment (and you're aware of the CORS errors you're likely to see from bybit's APIs), there's a webpack config that swaps node-support with browser-support, for the browser-equivalent of the crypto module:
https://github.com/tiagosiebler/bybit-api/blob/master/webpack/webpack.config.js#L18-L25
