### ISSUE TITLE
getPastOrders always throws recvWindow 

### ISSUE THREAD

**Issue by pranaypratyush** [tiagosiebler/bybit-api#167]
Getting the `Timestamp for this request is outside of the recvWindow.` error on `getPastOrders` regardless of anything. Other functions work.

**Comment by tiagosiebler** [comment]
Strange, which version are you using? Is this with the spot client?

**Comment by pranaypratyush** [comment]
yes, with  spotclient on master. I fail to understand how this is even possible.

**Comment by tiagosiebler** [comment]
Definitely strange, given how the abstraction layers work...and given there are integration tests on all endpoints. 

Can you try the latest beta release? It corresponds to the code currently in the open PR #166 
```
npm install bybit-api@2.4.0-beta.1
```

You have two choices here as well, there's the SpotClient (which uses the original v1 spot apis from the docs) and there's SpotClientV3 (the successor, which uses the newer v3 spot apis from the docs). 

I've tried to keep method naming consistent to reduce any transition pains as much as possible (from the v1 to v3 spot clients), but I would suggest to try both as there were under-the-hood refinements to how requests are built and authentication is handled. If there's a problem with auth in the current public release, it might be fixed in the beta release v1 client.

**Comment by tiagosiebler** [comment]
Closing this for now - the latest version (3.0.1 at time of writing) has tons of integration tests making real API calls, including this function, which is currently passing:
https://github.com/tiagosiebler/bybit-api/blob/master/test/spot/private.v3.read.test.ts#L38-L40

If the issue does somehow come back in the latest version, feel free to reopen. Thanks

**Comment by emorling** [comment]
I am using v3, and still get:

```
ret_code: 10002,
ret_msg: 'invalid request, please check your timestamp and recv_window param. 
req_timestamp: 1663797780831
server_timestamp: 1663797785964
recv_window: 5000',
```

I noticed these settings. Should I increase recv_window? and enable enable_time_sync? What do you recommend for sync_interval_ms?

```
/** Override the max size of the request window (in ms) */
    recv_window?: number;
    /** Disabled by default. This can help on machines with consistent latency problems. */
    enable_time_sync?: boolean;
    /** How often to sync time drift with bybit servers */
    sync_interval_ms?: number | string;
```

**Comment by tiagosiebler** [comment]
Timestamp errors are different, I wrote an explanation of this and why your system time & network is important:
https://github.com/tiagosiebler/awesome-crypto-examples/wiki/Timestamp-for-this-request-is-outside-of-the-recvWindow.

I'd suggest to try these, with each further step only a last resort if the previous step doesn't fix it:
- Ensure your time is manually in sync (using whatever time update/sync service your machine has - e.g. on macOS you can set time and date automatically).
- Ensure your machine is updating/syncing time automatically.
- Check that your network connection is stable.
- If it happens sometimes but not often, or if the above solutions still don't help, you can try increasing the recv window param in the config from the default 5000 ms (5 seconds). However, this should be a last resort since 5 seconds is already quite a gap.
- If it STILL happens, you can try to "enable_time_sync: true" but that should be a last resort as I've seen this cause more problems than it solves, eventually... I used to have it enabled by default in all my connectors, but I've seen that one slow request can offset it too far and start causing timestamp errors. That's why I'd prefer to keep it disabled.
