### ISSUE TITLE
Where is the contract closed-pnl endpoint?

### ISSUE THREAD

**Issue by lukese** [tiagosiebler/bybit-api#173]
Hi,

It says in the new 3.0 version that the full REST API and Websocket is completed but as far as I can see this endpoint found in the docs: https://bybit-exchange.github.io/docs/testnet/derivativesV3/contract/#t-dv_closedprofitandloss

Perhaps I am missing something? I'm happy to make a PR to add this but I'm not sure yet if maybe It's hidden somewhere or in another Bybit API?

**Comment by tiagosiebler** [comment]
The derivatives V3 group currently only has the v3 unified margin APIs added, since the v3 contract API hasn't reached the live environment yet. As you can see, also the docs only have v3 contract api docs in the testnet part of the site. I'll look to get this api group added to the connector soon as well. Should be really similar api calls to how the unified margin client works.

**Comment by tiagosiebler** [comment]
Hi, just pushed the new ContractClient for the contract v3 endpoints. It should be available on npm shortly as soon as the master branch finishes building. Here's the method in the contract client for this api call: https://github.com/tiagosiebler/bybit-api/blob/master/src/contract-client.ts#L288-L292
