### ISSUE TITLE
getOpenInterestLimitInfo has wrong api endpoint

### ISSUE THREAD

**Issue by VincentRuoka** [tiagosiebler/bybit-api#199]
/src/contract.client.ts:296 has wrong API endpoint:

is: /contract/v3/private/position/closed-pnl
should: /contract/v3/private/position/limit-info

Source: https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-oilimitinfo

**Comment by tiagosiebler** [comment]
Good catch! This slipped through while working on the new client. I'll get this updated. Seems something else is wrong with this endpoint too & I'm working with bybit to find what's missing.

**Comment by tiagosiebler** [comment]
Fixed in v3.3.1 (#201). Can you try it out? Seems it doesn't work on my account as I see the following error:
    +   "retCode": 10001,
    +   "retMsg": "params error: OI group don't exist",

But this seems to be an account-level issue (reproducible with code samples provided by bybit only using my api credentials). Working with bybit to understand the issue better (& get a better error message into that response). Would be curious if this works fine on your end. Thanks!
