### ISSUE TITLE
Server time sync error

### ISSUE THREAD

**Issue by MatheoG** [tiagosiebler/bybit-api#232]
I have this error message on V5: "invalid request, please check your server timestamp or recv_window param. req_timestamp[1677852615864132],server_timestamp[1677852616092],recv_window[5000]" on "getAccountInfo()"
The server ts is in second but req timestamp is in ms

**Comment by tiagosiebler** [comment]
The documentation does state the timestamp should be in milliseconds for v3-v5 authentication methods:
https://bybit-exchange.github.io/docs/v5/intro#parameters-for-authenticated-endpoints

Tests are also passing, authentication is working for signed endpoints. I do agree though, weird to see the mismatch between server and client timestamp on such a scale.

The unusual thing here is your request timestamp. Even if I deliberately force a request timestamp outside the recv window (e.g. 10 seconds ahead), my timestamp in milliseconds matches the format of the server timestamp:
```
{
  "retCode": 10002,
  "retMsg": "invalid request, please check your server timestamp or recv_window param. req_timestamp[1677853520948],server_timestamp[1677853421570],recv_window[5000]",
  "result": {},
  "retExtInfo": {},
  "time": 1677853421570
}
```

Typically recv window issues are caused by your system clock being slightly out of sync. In this case however, I wonder if it's something else. Do you by any chance have `enable_time_sync: true` in your instance of the RestClientV5? It's disabled by default, but I wonder if this is the cause - should you decided to enable it.

**Comment by MatheoG** [comment]
Yes it was activated, I had misunderstood how this parameter works

**Comment by tiagosiebler** [comment]
I see, I would also say it's not working as intended with v5 if the adjusted timestamp is on the wrong resolution..will look into it. Generally I would also recommend keeping this feature turned off - while it originally had good intentions, I've grown increasingly convinced it's causing more problems than it was originally solving and disabled it by default earlier last year.

If you do sometimes get the occasional recvwindow error, it would be better to have a service handle time sync for you within your operating system. E.g. https://ubuntu.com/server/docs/network-ntp
