### ISSUE TITLE
Documentation: typescript browser usage

### ISSUE THREAD

**Issue by Badisi** [tiagosiebler/bybit-api#258]
For anyone interested, this is how I managed to get the lib working with **typescript** in a **browser environment** (without the need to build it as suggested in the README).

1. Install these dependencies
    ```sh
    npm install crypto-browserify stream-browserify
    ```
2. Add this to your `tsconfig.json`
    ```json
    {
      "compilerOptions": {
        "paths": {
          "crypto": [
            "./node_modules/crypto-browserify"
          ],
          "stream": [
            "./node_modules/stream-browserify"
          ]
    }
    ```
3. Declare this in the global context of your application (ex: in polyfills for angular)
    ```js
    (window as any).global = window;
    ```

**Comment by Badisi** [comment]
@tiagosiebler, maybe this could be documented somewhere.

PS: I also think that the warning about CORS in the README could be removed as it seems it was resolved (and I did not encounter any issues with it myself)

**Comment by tiagosiebler** [comment]
This is wonderful, thank you for sharing this! I've wanted to explore a more friendly way of importing my SDKs in frontend projects but never got around to it. Do websockets work as well? 

Absolutely agree on the documentation, would like to get this added to the readme, since I think that's the first place many would look. Regarding CORS, also a good point - bybit added full CORS support, I think that was sometime last year.

**Comment by tiagosiebler** [comment]
Closing this, added it to readme a while ago
