### ISSUE TITLE
RestClientV5 is undefined

### ISSUE THREAD

**Issue by mmaestrini** [tiagosiebler/bybit-api#266]
All of a sudden when i try to instantiate a RestClientV5 i get undefined. no matter if test net or main net. Is there a way to know what is going on? there is no error message or anything shown...

**Comment by tiagosiebler** [comment]
Did something recently change on your end? Just to be sure, I just made a fresh project and installed the latest version. Simple JS file to test:
```javascript
const { RestClientV5 } = require('bybit-api');

console.log('class: ', { RestClientV5 });

const client = new RestClientV5({ key: 'asdfa', secret: 'asdfadsf' });

client
  .submitOrder({category: 'inverse', orderType: 'Limit', qty: 144, side: 'Buy', symbol: 'BTCUSD', price: 20000})
  .then((res) => console.log('res', res))
  .catch(e => console.error('e', e));
```

```log
$ node src/main.js
class:  { RestClientV5: [class RestClientV5 extends BaseRestClient] }
res {
  retCode: 10003,
  retMsg: 'API key is invalid.',
  result: {},
  retExtInfo: {},
  time: 1685693701999
}
```

Everything seems to be normal

**Comment by mmaestrini** [comment]
Bro I have no clue, I used to call a method called init() in my constructor where I did a bunch of things, amongst which 

```
this.botClientTestnet = await new RestClientV5(this.botClientConfigTestNet);
this.botClientProd = await new RestClientV5(Sugar.Object.clone(this.botClientConfigProd));
```

All of a sudden stopped - no clue why or what changed. I did learn i don't need await. 

Anyway, I did those 2 inits without the await keyword in the constructor before calling my init() and all is gucci.. So I have no clue why this worked and not in the init, or why it worked before and not now :/ And given that if it's undefined no message ir returned or logged i dunno :(

But I will close tho since it seems to be woring anyway this way now. Just very odd.

**Comment by tiagosiebler** [comment]
The constructor definitely does not need await since there's no asynchronous logic happening in there. All it does is set some initial state variables based on the params passed when you make a new rest client.

When something unclear like this is happening, it might be easier to investigate using breakpoints. In case you haven't tried attaching a debugger to a nodejs project before, here's some info that still applies:
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27
https://nodejs.org/en/docs/guides/debugging-getting-started

This allows you to pause execution and inspect variables (or maybe your execution never reaches that bit for some reason).

**Comment by mmaestrini** [comment]
I have a debugger but didnt try to step into the library when it intialized the client actually... I did it for other things in the past - go figure why i didnt try it now for this :P nha I debugged it until past init and that is how i could see it was undefined. I will investigate it tho since it used to work, so i will revert and see what it might have been just out of curiousity - tho i will keep the code working as now.

thanks!
