### ISSUE TITLE
got Uncaught (in promise) TypeError: (0 , crypto_1.createHmac) is not a function

### ISSUE THREAD

**Issue by smishnev** [tiagosiebler/bybit-api#328]
this is my code

```
const client = new RestClientV5({
  key: APIKEY,
  secret: APISECRET,
});

async function fetchWalletBalance() {
  return await client.getWalletBalance({
    accountType: "SPOT",
  });
}
async function fetchW() {
  return await client.getKline({
    category: "linear",
    interval: "15",
    symbol: "BTCUSDT",
  });
}

function ByBit() {
  const [data, setData] = useState<any>(null);

  useEffect(() => {
    async function fetchData() {
      const walletBalance = await fetchWalletBalance();
      setData(walletBalance);
    }

    fetchData();

    // Cleanup function
    return () => {
      // Any cleanup code if needed
    };
  }, []);

  console.log("data", data);

  return (
    <div className="container">
      {data ? (
        <>
          <div>Data</div>
        </>
      ) : (
        <div>Loading...</div>
      )}
    </div>
  );
}
```

but if try look this request fetchW i got information, but when i want look fetchWalletBalance i have this error

![image](https://github.com/tiagosiebler/bybit-api/assets/84381256/7147390b-1d3a-40a3-92af-f38307e0c7ad)

**Comment by tiagosiebler** [comment]
This is happening because the library used for the signature (authentication) is a node.js lib, which isn't available in the browser. Some users have reported using "crypto-browserify" instead. There's different ways to tell your build to use "crypto-browserify" instead of "crypto". E.g. if you're using typescript, here's one approach:
https://github.com/tiagosiebler/bybit-api?tab=readme-ov-file#browser-usage

**Comment by smishnev** [comment]
Thank you, will try
