### ISSUE TITLE
fundingRate missing in ticker delta events

### ISSUE THREAD

**Issue by davidpccu** [tiagosiebler/bybit-api#329]
In the V5 API version, subscribe to the Public ticker stream via WebSocket In Linear/Inverse, the Response is missing the fundingRate field.
[https://bybit-exchange.github.io/docs/v5/websocket/public/ticker](url)

**Comment by tiagosiebler** [comment]
Hey @davidpccu 

Did a quick test, it's shown in the first snapshot event when first subscribing:
<img width="297" alt="Screenshot 2024-04-18 at 13 54 11" src="https://github.com/tiagosiebler/bybit-api/assets/14090872/a9ed38bc-5f1b-406b-93a5-e0f86e1ea567">

The delta events don't seem to always include all of the fields. Seems like it's designed to only include a field when that value changed:
<img width="454" alt="Screenshot 2024-04-18 at 13 54 53" src="https://github.com/tiagosiebler/bybit-api/assets/14090872/9f0a2c00-4fed-4eea-8e43-7f8367fea5bb">

So if you don't see `fundingRate`, you can assume that value hasn't changed since the last time you saw the funding rate field

**Comment by tiagosiebler** [comment]
The docs confirm this:
"This topic utilises the snapshot field and delta field. If a response param is not found in the message, then its value has not changed."

https://bybit-exchange.github.io/docs/v5/websocket/public/ticker
