### ISSUE TITLE
Get Server Time and Typings

### ISSUE THREAD

**Issue by Perlzx** [tiagosiebler/bybit-api#333]
Hello, I got troubles with syncTimeBeforePrivateRequests parameter in RestClientV5 namely in lib/util/requestUtils.d.ts
```
export interface RestClientOptions {
...
    /** Determines whether to perform time synchronization before sending private requests */
    syncTimeBeforePrivateRequests?: false;
...
}
```

need change to syncTimeBeforePrivateRequests?: **boolean**;

Also got trouble with **getServerTime** function in RestClientV5
because they changed response of **/v3/public/time** and for now should be used **/v5/market/time**

**Comment by tiagosiebler** [comment]
Hi @Perlzx thanks for raising this issue. 

Keep in mind that I don't normally recommend using something like `syncTimeBeforePrivateRequests`. The automatic & experimental time sync feature is also disabled by default for a few years now, because in my experience it causes more problems than it solves. One very slow time-sync request can create a bad offset for many future requests, causing a burst of failing requests instead of just one or two failing requests.

If you're seeing recv window (ret code 10002) errors frequently, it's much more reliable to ensure you have network time synchronisation enabled on the operating system where your code is running. Lots of guidance here on how to approach this:
https://github.com/tiagosiebler/awesome-crypto-examples/wiki/Timestamp-for-this-request-is-outside-of-the-recvWindow

Nevertheless, the issues you have reported are two mistakes that will be fixed shortly in v3.10.1, via #335. They will remain disabled by default but if you wish to experiment with them they should be working again once the update reaches npm in a few minutes.
