### ISSUE TITLE
position idx not match position mode

### ISSUE THREAD

**Issue by ne0c0de** [tiagosiebler/bybit-api#363]
Hi

I'm getting this error: ```position idx not match position mode``` when I'm trying to open a position on bybit with usual parameters.  (something like ```  {
    category: 'linear',
    symbol: 'CRVUSDT',
    side: 'Buy',
    orderType: 'Market',
    qty: '465.2',
    orderLinkId: 'CTB_1722682067_MANUAL_ENTRY'
  }```)

What should I need to do?

**Comment by tiagosiebler** [comment]
Hi @ne0c0de 

This happens when your position mode is set to hedge mode (allowing you to simultaneously have a long and a short position on the same symbol, if you wanted to). You can either change to one-way mode: 
https://github.com/tiagosiebler/bybit-api/blob/master/src/rest-client-v5.ts#L665

Or, include the "
positionIdx" parameter with your order. More info on positionIdx is here: https://bybit-exchange.github.io/docs/v5/order/create-order#request-parameters
