### ISSUE TITLE
Add support for multiple accounts in ws client

### ISSUE THREAD

**Issue by SebastianBoehler** [tiagosiebler/bybit-api#388]
Support for multiple accounts like in the okx-api in the ws client

**Comment by tiagosiebler** [comment]
For OKX, this is actually made possible because their implementation supports multiple accounts on one connection:
https://www.okx.com/docs-v5/en/#overview-websocket-login

This is unfortunately not possible for bybit, at least not in the form of multiple sessions on one private WS connection. Best way forward here is to spawn multiple WS clients, one per-account. 

While connecting event handlers for each WS client, you can then also use lexical scoping to enrich incoming events so you know which ws-client instance (& account) each event corresponds to.

**Comment by SebastianBoehler** [comment]
Thanks. Alright then I am taking this approach, hadn't looked into the specifics of the OKX logic and thought maybe it works there like this already by handling multiple clients
